CREATE TABLE IF NOT EXISTS pisces_event_replay_job (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    replay_job_id VARCHAR(64) NOT NULL COMMENT '重放任务ID',
    experiment_id VARCHAR(64) NOT NULL COMMENT '实验ID',
    operator VARCHAR(128) DEFAULT NULL COMMENT '操作人',
    job_status VARCHAR(32) NOT NULL COMMENT 'RUNNING / CANCEL_REQUESTED / SUCCEEDED / FAILED / CANCELLED',
    active_key VARCHAR(64) DEFAULT NULL COMMENT '运行中互斥键，运行或取消待确认时为experiment_id，结束后置空',
    replay_mode VARCHAR(64) NOT NULL DEFAULT 'FULL_DERIVED_REBUILD' COMMENT '重放模式',
    scope_start_time DATETIME DEFAULT NULL COMMENT '重放范围开始时间',
    scope_end_time DATETIME DEFAULT NULL COMMENT '重放范围结束时间',
    event_types_json VARCHAR(1024) DEFAULT NULL COMMENT '事件类型筛选JSON',
    include_events TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否包含事件事实',
    include_exposures TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否包含曝光事实',
    full_derived_replay TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否等价全量派生重建',
    planned_affected_count BIGINT NOT NULL DEFAULT 0 COMMENT '计划处理总事实数',
    planned_event_count BIGINT NOT NULL DEFAULT 0 COMMENT '计划处理事件事实数',
    planned_exposure_count BIGINT NOT NULL DEFAULT 0 COMMENT '计划处理曝光事实数',
    planned_group_count BIGINT NOT NULL DEFAULT 0 COMMENT '计划处理实验组数',
    affected_count BIGINT NOT NULL DEFAULT 0 COMMENT '重建影响记录数',
    event_count BIGINT NOT NULL DEFAULT 0 COMMENT '重建事件事实数',
    exposure_count BIGINT NOT NULL DEFAULT 0 COMMENT '重建曝光事实数',
    group_count BIGINT NOT NULL DEFAULT 0 COMMENT '重建实验组数',
    mab_reward_count BIGINT NOT NULL DEFAULT 0 COMMENT '重建MAB奖励数',
    error_message VARCHAR(1024) DEFAULT NULL COMMENT '失败原因',
    started_at DATETIME NOT NULL COMMENT '开始时间',
    finished_at DATETIME DEFAULT NULL COMMENT '结束时间',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_replay_job_id (replay_job_id),
    UNIQUE KEY uk_replay_active_key (active_key),
    KEY idx_replay_experiment_status (experiment_id, job_status, id),
    KEY idx_replay_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Pisces事件管道重放任务表';
