CREATE TABLE IF NOT EXISTS pisces_application_space (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    app_id VARCHAR(128) NOT NULL COMMENT '应用ID',
    display_name VARCHAR(128) DEFAULT NULL COMMENT '展示名称',
    default_owner VARCHAR(128) DEFAULT NULL COMMENT '默认负责人',
    experiment_quota INT DEFAULT NULL COMMENT '实验配额，NULL表示不限制',
    is_approval_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '配置发布/启动实验是否需要审批：1是，0否',
    approval_owners VARCHAR(512) DEFAULT NULL COMMENT '配置发布/启动审批人列表，英文逗号分隔',
    approval_required_count INT NOT NULL DEFAULT 1 COMMENT '审批通过所需人数',
    approval_policy_version BIGINT NOT NULL DEFAULT 1 COMMENT '审批策略版本',
    approval_sla_hours INT DEFAULT NULL COMMENT '审批SLA小时数，NULL表示不启用',
    approval_escalation_owners VARCHAR(512) DEFAULT NULL COMMENT '审批升级接收人列表，英文逗号分隔',
    is_release_window_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用发布窗口：1是，0否',
    release_window_timezone VARCHAR(64) DEFAULT NULL COMMENT '发布窗口时区，如 Asia/Shanghai',
    release_window_days VARCHAR(64) DEFAULT NULL COMMENT '发布窗口星期列表，1=周一，7=周日，英文逗号分隔',
    release_window_start_time VARCHAR(5) DEFAULT NULL COMMENT '发布窗口开始时间，格式HH:mm',
    release_window_end_time VARCHAR(5) DEFAULT NULL COMMENT '发布窗口结束时间，格式HH:mm',
    created_by VARCHAR(128) NOT NULL COMMENT '创建人',
    updated_by VARCHAR(128) NOT NULL COMMENT '更新人',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_app_id (app_id),
    KEY idx_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Pisces应用空间注册表';
