CREATE TABLE IF NOT EXISTS pisces_event_inbox (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    inbox_id VARCHAR(64) NOT NULL COMMENT '内部事件ID',
    experiment_id VARCHAR(64) NOT NULL COMMENT '实验ID',
    visitor_id VARCHAR(128) NOT NULL COMMENT '访客ID',
    group_id VARCHAR(64) DEFAULT NULL COMMENT '实验组ID',
    event_kind VARCHAR(32) NOT NULL COMMENT 'EVENT / EXPOSURE',
    event_type VARCHAR(64) DEFAULT NULL COMMENT '事件类型',
    event_name VARCHAR(128) DEFAULT NULL COMMENT '事件名称',
    scene VARCHAR(128) DEFAULT NULL COMMENT '曝光场景',
    client_event_id VARCHAR(128) DEFAULT NULL COMMENT '客户端幂等事件ID',
    idempotency_key VARCHAR(255) NOT NULL COMMENT '幂等键',
    properties_json LONGTEXT DEFAULT NULL COMMENT '原始属性JSON',
    status VARCHAR(32) NOT NULL COMMENT 'PENDING / PROCESSING / RETRY / DONE / DEAD / REJECTED',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    next_retry_at DATETIME NOT NULL COMMENT '下次处理时间',
    locked_by VARCHAR(128) DEFAULT NULL COMMENT '处理节点',
    locked_until DATETIME DEFAULT NULL COMMENT '锁过期时间',
    last_error VARCHAR(1024) DEFAULT NULL COMMENT '最后失败原因',
    event_time DATETIME NOT NULL COMMENT '业务事件时间',
    accepted_at DATETIME NOT NULL COMMENT '受理时间',
    processed_at DATETIME DEFAULT NULL COMMENT '处理完成时间',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_inbox_id (inbox_id),
    UNIQUE KEY uk_inbox_idempotency (idempotency_key),
    KEY idx_inbox_status_retry (status, next_retry_at, id),
    KEY idx_inbox_experiment_status (experiment_id, status, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Pisces事件采集inbox表';
