#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/production-infrastructure-local-dependency-stack.sh [up|down|status|config]

Environment:
  PISCES_REPO_ROOT                         Repository root. Default: inferred from this script.
  PISCES_LOCAL_STACK_COMPOSE_FILE          Compose file. Default: compose.local.yml.
  PISCES_LOCAL_STACK_ENV_FILE              Generated stack env file. Default: config/pisces-local-stack.env.
  PISCES_LOCAL_STACK_OUTPUT_FILE           JSON output. Default: target/pisces-production-infrastructure-local-stack/summary.json.
  PISCES_LOCAL_STACK_PROJECT_NAME          Compose project name. Default: pisces-local.
  PISCES_LOCAL_STACK_AUTO_PORTS            Pick fallback ports when defaults are busy. Default: true.
  PISCES_LOCAL_STACK_DRY_RUN               Write plan only, do not call Docker. Default: false.
  PISCES_LOCAL_STACK_WAIT                  Use docker compose up --wait when supported. Default: true.
  PISCES_LOCAL_MYSQL_PORT                  Host MySQL port. Default: 3306 or fallback 13306+.
  PISCES_LOCAL_REDIS_PORT                  Host Redis port. Default: 6379 or fallback 16379+.
  PISCES_LOCAL_ZOOKEEPER_PORT              Host Zookeeper port. Default: 2181 or fallback 12181+.
  PISCES_LOCAL_MYSQL_DATABASE              MySQL database. Default: pisces.

The script writes config/pisces-local-stack.env with MYSQL_URL, Redis, and
Zookeeper overrides for the chosen local stack ports. The file is ignored by git
and is automatically read by the local schema/dependency scripts.
USAGE
}

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%dT%H:%M:%S%z')" "$*" >&2
}

die() {
  log "ERROR: $*"
  exit 1
}

is_true() {
  case "${1:-}" in
    true|TRUE|True|1|yes|YES|Yes|y|Y)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

resolve_repo_root() {
  if [[ -n "${PISCES_REPO_ROOT:-}" ]]; then
    (cd "$PISCES_REPO_ROOT" && pwd)
    return
  fi

  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if command -v git >/dev/null 2>&1 && git -C "$script_dir/.." rev-parse --show-toplevel >/dev/null 2>&1; then
    git -C "$script_dir/.." rev-parse --show-toplevel
    return
  fi
  (cd "$script_dir/.." && pwd)
}

resolve_path() {
  case "$1" in
    /*)
      printf '%s' "$1"
      ;;
    *)
      printf '%s/%s' "$PISCES_REPO_ROOT" "$1"
      ;;
  esac
}

display_path() {
  python3 - "$PISCES_REPO_ROOT" "$1" <<'PY'
import sys
from pathlib import Path

repo = Path(sys.argv[1]).resolve()
path = Path(sys.argv[2]).resolve()
try:
    print(path.relative_to(repo))
except ValueError:
    print(path)
PY
}

select_port() {
  local preferred="$1"
  local fallback_start="$2"
  local auto_ports="$3"
  python3 - "$preferred" "$fallback_start" "$auto_ports" <<'PY'
import socket
import sys

preferred = int(sys.argv[1])
fallback_start = int(sys.argv[2])
auto_ports = sys.argv[3].lower() in {"true", "1", "yes", "y"}


def is_busy(port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.2)
        return sock.connect_ex(("127.0.0.1", port)) == 0


if not auto_ports or not is_busy(preferred):
    print(preferred)
    raise SystemExit(0)

for candidate in range(fallback_start, fallback_start + 100):
    if not is_busy(candidate):
        print(candidate)
        raise SystemExit(0)

raise SystemExit(f"no available local port from {fallback_start} to {fallback_start + 99}")
PY
}

write_stack_env() {
  local env_file="$1"
  mkdir -p "$(dirname "$env_file")"
  python3 - "$env_file" <<'PY'
import os
import sys
from pathlib import Path

env_file = Path(sys.argv[1])
mysql_port = os.environ["PISCES_LOCAL_MYSQL_PORT"]
redis_port = os.environ["PISCES_LOCAL_REDIS_PORT"]
zookeeper_port = os.environ["PISCES_LOCAL_ZOOKEEPER_PORT"]
database = os.environ["PISCES_LOCAL_MYSQL_DATABASE"]
project_name = os.environ["PISCES_LOCAL_STACK_PROJECT_NAME"]
compose_file = os.environ["PISCES_LOCAL_STACK_COMPOSE_FILE_RESOLVED"]

text = f"""# Generated by scripts/production-infrastructure-local-dependency-stack.sh.
# This file contains local-only dependency port overrides and is ignored by git.

export PISCES_LOCAL_STACK_PROJECT_NAME="{project_name}"
export PISCES_LOCAL_STACK_COMPOSE_FILE="{compose_file}"
export PISCES_LOCAL_MYSQL_PORT="{mysql_port}"
export PISCES_LOCAL_REDIS_PORT="{redis_port}"
export PISCES_LOCAL_ZOOKEEPER_PORT="{zookeeper_port}"
export PISCES_LOCAL_MYSQL_DATABASE="{database}"

export MYSQL_URL="jdbc:mysql://localhost:{mysql_port}/{database}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
export MYSQL_USERNAME="root"
export MYSQL_PASSWORD=""

export SPRING_DATA_REDIS_HOST="localhost"
export SPRING_DATA_REDIS_PORT="{redis_port}"
export SPRING_DATA_REDIS_TIMEOUT="300ms"
export PISCES_ZOOKEEPER_CONNECT_STRING="localhost:{zookeeper_port}"
export PISCES_REDIS_DOCKER_CONTAINER="{project_name}-redis-1"
"""
env_file.write_text(text, encoding="utf-8")
PY
  chmod 600 "$env_file" 2>/dev/null || true
}

compose_base_command() {
  printf 'docker compose --project-name %q -f %q' \
    "$PISCES_LOCAL_STACK_PROJECT_NAME" \
    "$PISCES_LOCAL_STACK_COMPOSE_FILE_RESOLVED"
}

write_summary() {
  local status="$1"
  local action="$2"
  local exit_code="$3"
  local message="$4"
  local docker_output_file="$5"
  python3 - "$status" "$action" "$exit_code" "$message" "$docker_output_file" <<'PY'
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

status, action, exit_code, message, docker_output_file = sys.argv[1:6]
repo_root = Path(os.environ["PISCES_REPO_ROOT"])
output_file = Path(os.environ["PISCES_LOCAL_STACK_OUTPUT_FILE_RESOLVED"])
compose_file = Path(os.environ["PISCES_LOCAL_STACK_COMPOSE_FILE_RESOLVED"])
env_file = Path(os.environ["PISCES_LOCAL_STACK_ENV_FILE_RESOLVED"])
docker_output = Path(docker_output_file)


def display(path):
    try:
        return str(path.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        return str(path)


mysql_port = int(os.environ["PISCES_LOCAL_MYSQL_PORT"])
redis_port = int(os.environ["PISCES_LOCAL_REDIS_PORT"])
zookeeper_port = int(os.environ["PISCES_LOCAL_ZOOKEEPER_PORT"])
next_commands = []
if status == "PLAN_ONLY":
    next_commands.append("bash scripts/production-infrastructure-local-dependency-stack.sh up")
if action == "up" and status in {"PLAN_ONLY", "STARTED"}:
    next_commands.extend([
        "source config/pisces-local.env",
        f"source {display(env_file)}",
        "bash scripts/production-infrastructure-local-mysql-schema-apply.sh",
        "bash scripts/production-infrastructure-local-dependency-check.sh",
        "bash scripts/production-infrastructure-local-service.sh start",
        "bash scripts/production-infrastructure-local-readiness.sh",
    ])
elif action == "down":
    next_commands.append("bash scripts/production-infrastructure-local-dependency-stack.sh up")

summary = {
    "summaryType": "pisces-production-infrastructure-local-dependency-stack",
    "summaryVersion": 1,
    "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "status": status,
    "targetEnvironment": "local",
    "action": action,
    "exitCode": int(exit_code),
    "dryRun": os.environ["PISCES_LOCAL_STACK_DRY_RUN"].lower() in {"true", "1", "yes", "y"},
    "autoPorts": os.environ["PISCES_LOCAL_STACK_AUTO_PORTS"].lower() in {"true", "1", "yes", "y"},
    "composeProject": os.environ["PISCES_LOCAL_STACK_PROJECT_NAME"],
    "composeFile": display(compose_file),
    "stackEnvFile": display(env_file),
    "database": os.environ["PISCES_LOCAL_MYSQL_DATABASE"],
    "ports": {
        "mysql": mysql_port,
        "redis": redis_port,
        "zookeeper": zookeeper_port,
    },
    "portOverrides": {
        "mysql": mysql_port != 3306,
        "redis": redis_port != 6379,
        "zookeeper": zookeeper_port != 2181,
    },
    "dockerComposeCommand": os.environ["PISCES_LOCAL_STACK_LAST_COMMAND"],
    "dockerOutputFile": display(docker_output),
    "message": message,
    "nextCommands": next_commands,
}
output_file.write_text(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(
    f"Production infrastructure local dependency stack written: {output_file} status={status} action={action}",
    file=sys.stderr,
)
PY
}

run_docker_compose() {
  local action="$1"
  local docker_output_file="$2"
  local -a command_args=(
    docker compose
    --project-name "$PISCES_LOCAL_STACK_PROJECT_NAME"
    -f "$PISCES_LOCAL_STACK_COMPOSE_FILE_RESOLVED"
  )

  case "$action" in
    up)
      command_args+=(up -d)
      if is_true "$PISCES_LOCAL_STACK_WAIT" && docker compose up --help 2>/dev/null | grep -q -- '--wait'; then
        command_args+=(--wait)
      fi
      ;;
    down)
      command_args+=(down)
      ;;
    status)
      command_args+=(ps)
      ;;
    config)
      command_args+=(config)
      ;;
    *)
      die "Unsupported action: $action"
      ;;
  esac

  printf '%q ' "${command_args[@]}" >"$docker_output_file.command"
  PISCES_LOCAL_STACK_LAST_COMMAND="$(cat "$docker_output_file.command")"
  export PISCES_LOCAL_STACK_LAST_COMMAND
  "${command_args[@]}" >"$docker_output_file" 2>&1
}

main() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
  fi

  command -v python3 >/dev/null 2>&1 || die "Missing command: python3"

  local action="${1:-up}"
  case "$action" in
    up|down|status|config)
      ;;
    *)
      usage >&2
      die "Unsupported action: $action"
      ;;
  esac

  local env_compose_file
  env_compose_file="${PISCES_LOCAL_STACK_COMPOSE_FILE-}"

  PISCES_REPO_ROOT="$(resolve_repo_root)"
  PISCES_LOCAL_STACK_COMPOSE_FILE="${PISCES_LOCAL_STACK_COMPOSE_FILE:-compose.local.yml}"
  PISCES_LOCAL_STACK_ENV_FILE="${PISCES_LOCAL_STACK_ENV_FILE:-config/pisces-local-stack.env}"
  PISCES_LOCAL_STACK_OUTPUT_FILE="${PISCES_LOCAL_STACK_OUTPUT_FILE:-target/pisces-production-infrastructure-local-stack/summary.json}"
  PISCES_LOCAL_STACK_PROJECT_NAME="${PISCES_LOCAL_STACK_PROJECT_NAME:-pisces-local}"
  PISCES_LOCAL_STACK_AUTO_PORTS="${PISCES_LOCAL_STACK_AUTO_PORTS:-true}"
  PISCES_LOCAL_STACK_DRY_RUN="${PISCES_LOCAL_STACK_DRY_RUN:-false}"
  PISCES_LOCAL_STACK_WAIT="${PISCES_LOCAL_STACK_WAIT:-true}"

  local output_file compose_file stack_env_file stack_dir docker_output_file
  output_file="$(resolve_path "$PISCES_LOCAL_STACK_OUTPUT_FILE")"
  stack_env_file="$(resolve_path "$PISCES_LOCAL_STACK_ENV_FILE")"
  stack_dir="$(dirname "$output_file")"
  docker_output_file="$stack_dir/docker-compose-output.txt"
  mkdir -p "$stack_dir"

  local env_mysql_port env_redis_port env_zookeeper_port env_database env_project
  env_mysql_port="${PISCES_LOCAL_MYSQL_PORT-}"
  env_redis_port="${PISCES_LOCAL_REDIS_PORT-}"
  env_zookeeper_port="${PISCES_LOCAL_ZOOKEEPER_PORT-}"
  env_database="${PISCES_LOCAL_MYSQL_DATABASE-}"
  env_project="${PISCES_LOCAL_STACK_PROJECT_NAME-}"

  if [[ -f "$stack_env_file" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$stack_env_file"
    set +a
  fi

  [[ -n "$env_compose_file" ]] && PISCES_LOCAL_STACK_COMPOSE_FILE="$env_compose_file"
  [[ -n "$env_mysql_port" ]] && PISCES_LOCAL_MYSQL_PORT="$env_mysql_port"
  [[ -n "$env_redis_port" ]] && PISCES_LOCAL_REDIS_PORT="$env_redis_port"
  [[ -n "$env_zookeeper_port" ]] && PISCES_LOCAL_ZOOKEEPER_PORT="$env_zookeeper_port"
  [[ -n "$env_database" ]] && PISCES_LOCAL_MYSQL_DATABASE="$env_database"
  [[ -n "$env_project" ]] && PISCES_LOCAL_STACK_PROJECT_NAME="$env_project"

  PISCES_LOCAL_MYSQL_DATABASE="${PISCES_LOCAL_MYSQL_DATABASE:-pisces}"
  PISCES_LOCAL_MYSQL_PORT="${PISCES_LOCAL_MYSQL_PORT:-$(select_port 3306 13306 "$PISCES_LOCAL_STACK_AUTO_PORTS")}"
  PISCES_LOCAL_REDIS_PORT="${PISCES_LOCAL_REDIS_PORT:-$(select_port 6379 16379 "$PISCES_LOCAL_STACK_AUTO_PORTS")}"
  PISCES_LOCAL_ZOOKEEPER_PORT="${PISCES_LOCAL_ZOOKEEPER_PORT:-$(select_port 2181 12181 "$PISCES_LOCAL_STACK_AUTO_PORTS")}"
  compose_file="$(resolve_path "$PISCES_LOCAL_STACK_COMPOSE_FILE")"
  [[ -f "$compose_file" ]] || die "Missing compose file: $compose_file"

  PISCES_LOCAL_STACK_COMPOSE_FILE_RESOLVED="$compose_file"
  PISCES_LOCAL_STACK_ENV_FILE_RESOLVED="$stack_env_file"
  PISCES_LOCAL_STACK_OUTPUT_FILE_RESOLVED="$output_file"
  PISCES_LOCAL_STACK_LAST_COMMAND="$(compose_base_command) $action"

  export PISCES_REPO_ROOT
  export PISCES_LOCAL_STACK_PROJECT_NAME
  export PISCES_LOCAL_STACK_AUTO_PORTS
  export PISCES_LOCAL_STACK_DRY_RUN
  export PISCES_LOCAL_STACK_WAIT
  export PISCES_LOCAL_STACK_COMPOSE_FILE_RESOLVED
  export PISCES_LOCAL_STACK_ENV_FILE_RESOLVED
  export PISCES_LOCAL_STACK_OUTPUT_FILE_RESOLVED
  export PISCES_LOCAL_STACK_LAST_COMMAND
  export PISCES_LOCAL_MYSQL_PORT
  export PISCES_LOCAL_REDIS_PORT
  export PISCES_LOCAL_ZOOKEEPER_PORT
  export PISCES_LOCAL_MYSQL_DATABASE

  write_stack_env "$stack_env_file"

  if is_true "$PISCES_LOCAL_STACK_DRY_RUN"; then
    printf 'dry-run: %s\n' "$PISCES_LOCAL_STACK_LAST_COMMAND" >"$docker_output_file"
    write_summary "PLAN_ONLY" "$action" 0 "Dry run only; Docker was not called." "$docker_output_file"
    return 0
  fi

  if ! command -v docker >/dev/null 2>&1; then
    printf 'Missing command: docker\n' >"$docker_output_file"
    write_summary "DOCKER_UNAVAILABLE" "$action" 127 "Install or start Docker Desktop, then rerun this script." "$docker_output_file"
    return 2
  fi

  set +e
  run_docker_compose "$action" "$docker_output_file"
  local compose_status=$?
  set -e

  if [[ "$compose_status" -ne 0 ]]; then
    write_summary "FAILED" "$action" "$compose_status" "docker compose command failed; inspect dockerOutputFile." "$docker_output_file"
    return "$compose_status"
  fi

  local status message
  case "$action" in
    up)
      status="STARTED"
      message="Local MySQL, Redis, and Zookeeper stack requested via Docker Compose."
      ;;
    down)
      status="STOPPED"
      message="Local Docker Compose dependency stack stopped."
      ;;
    status)
      status="STATUS_RECORDED"
      message="Local Docker Compose dependency stack status recorded."
      ;;
    config)
      status="CONFIG_RENDERED"
      message="Local Docker Compose dependency stack config rendered."
      ;;
  esac
  write_summary "$status" "$action" 0 "$message" "$docker_output_file"
}

main "$@"
